### ISSUE TITLE
Play in no internet?

### ISSUE THREAD

**Issue by ammarx** [tomsik68/mclauncher-api#21]
Um I am not sure if that part is implemented or not (so this is sort of a suggestion).. I tried looking for it but couldn't find it. Here is what I mean...
If the user has no internet connection, the details about the minecraft version can not be resolved. 
Example:
```
IVersion changed = null;
            try {
                changed = versionList.retrieveVersionInfo("1.8");
            } catch (Exception e) {
                e.printStackTrace();
            }
```

Is the example over here: https://github.com/tomsik68/mclauncher-api/blob/master/src/test/java/TestMCDownloadLaunch.java

If I go into the function retrieveVersionInfo which has code:

```
@Override
    public IVersion retrieveVersionInfo(String id) throws Exception{
        String fullVersionJSONString = HttpUtils.httpGet(FULL_VERSION_URL_TEMPLATE.replace("<VERSION>", id));
        JSONObject fullVersionObject = (JSONObject) JSONValue.parse(fullVersionJSONString);
        // ,create a MCDownloadVersion based on it
        MCDownloadVersion version = new MCDownloadVersion(fullVersionObject);
        // resolve inheritance if needed
        resolveInheritance(version);
        return version;
    }
```

Now over here its trying to connect to the internet.. So the user won't be able to play minecraft if no internet is available.. (tested it..)

As again.. I am not sure if this is something thats not implemented, I just wanted to give suggestion.

Regards,
Ammar Ahmad

**Comment by ammarx** [comment]
A simple fix could be to store those files on users computer and read from there if no internet is available..

**Comment by tomsik68** [comment]
Yeah, the files are stored and previous(I guess older than b5861f27d) versions didn't really care about the stored files.
Anyway, if you look at the current commit, MCDownloadVersionList now uses 2 different package-visible classes - MCDownloadOnlineVersionList and MCDownloadLocalVersionList. In case user already has the version installed MCDownloadOnlineVersionList(the thing that uses HttpUtils.httpGet) is never called.
https://github.com/tomsik68/mclauncher-api/blob/master/src/main/java/sk/tomsik68/mclauncher/impl/versions/mcdownload/MCDownloadVersionList.java#L40
Current commit still doesn't support offline play, but it's because of sessions. You can't create an ISession object without logging in via a LoginService.

**Comment by ammarx** [comment]
Alright, cool! I should be able to rewrite some part of the library to support the offline services. Thanks for the help.
