### ISSUE TITLE
MCLib patching support? (Fabric)

### ISSUE THREAD

**Issue by kz-n** [tomsik68/mclauncher-api#68]
Have been searching through dozens of repos, trying to find a library that supports this:
Can you use fabric here? And I mean being able to patch a fabric .jar with minecraft and running it.

**Comment by JakobDev** [comment]
Patching with fabric is really easy, because the fabric installer can be run with [Commandline Arguments](https://fabricmc.net/wiki/install#cli_installation). All what you have to do is to download the fabric installer and run it with the right arguments. If you know Python, you can port the code from [my python lib](https://gitlab.com/JakobDev/minecraft-launcher-lib/blob/master/minecraft_launcher_lib/fabric.py#L77) to Java.

**Comment by kz-n** [comment]
@JakobDev From what I understand the fabric installer doesn't do any actual patching, it is up to your launcher.
